// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP8z6AZ9hjqwFO00nQXBB3MWs483Rg5II',
    appId: '1:978051850630:web:208edd5bcc229f639b8c07',
    messagingSenderId: '978051850630',
    projectId: 'app-orcamente',
    authDomain: 'app-orcamente.firebaseapp.com',
    storageBucket: 'app-orcamente.firebasestorage.app',
    measurementId: 'G-886ZM2SWT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTJYISiRWT41p6Uqru3AlTPoV5rlz8fY',
    appId: '1:978051850630:android:88a6c044d00e56539b8c07',
    messagingSenderId: '978051850630',
    projectId: 'app-orcamente',
    storageBucket: 'app-orcamente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwIv27z1_YWHgBchKSzbHi2greIs5nzMo',
    appId: '1:978051850630:ios:04ab31382407a2ba9b8c07',
    messagingSenderId: '978051850630',
    projectId: 'app-orcamente',
    storageBucket: 'app-orcamente.firebasestorage.app',
    iosBundleId: 'com.example.orcamente',
  );
}
